remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-titles-from-headings

include: ["_pages"]

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      permalink: /:path/

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
